# Generated by Django 2.2.1 on 2019-05-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('arduino_id', models.CharField(max_length=50, verbose_name='Arduino device id')),
                ('humidity', models.IntegerField(max_length=3)),
                ('temperature', models.IntegerField(max_length=3)),
                ('light', models.IntegerField(max_length=4)),
                ('longitude', models.CharField(max_length=7)),
                ('latitude', models.CharField(max_length=7)),
            ],
        ),
    ]
