# Generated by Django 2.2.1 on 2019-05-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='arduino_id',
            new_name='ard_id',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='light',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='hum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='lat',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='lig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='lon',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
