# Generated by Django 2.2.1 on 2019-05-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_auto_20190516_1920'),
        ('manage', '0003_auto_20190528_0805'),
    ]

    operations = [
    ]
